/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VentRouteImport } from './routes/vent'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechniquesRouteImport } from './routes/techniques'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaceRouteImport } from './routes/face'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as IndexRouteImport } from './routes/index'

const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VentRoute = VentRouteImport.update({
  id: '/vent',
  path: '/vent',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniquesRoute = TechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceRoute = FaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/face': typeof FaceRoute
  '/journal': typeof JournalRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/techniques': typeof TechniquesRoute
  '/terms': typeof TermsRoute
  '/vent': typeof VentRoute
  '/verify': typeof VerifyRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/face': typeof FaceRoute
  '/journal': typeof JournalRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/techniques': typeof TechniquesRoute
  '/terms': typeof TermsRoute
  '/vent': typeof VentRoute
  '/verify': typeof VerifyRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRoute
  '/face': typeof FaceRoute
  '/journal': typeof JournalRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/techniques': typeof TechniquesRoute
  '/terms': typeof TermsRoute
  '/vent': typeof VentRoute
  '/verify': typeof VerifyRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breathe'
    | '/face'
    | '/journal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/techniques'
    | '/terms'
    | '/vent'
    | '/verify'
    | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breathe'
    | '/face'
    | '/journal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/techniques'
    | '/terms'
    | '/vent'
    | '/verify'
    | '/walk'
  id:
    | '__root__'
    | '/'
    | '/breathe'
    | '/face'
    | '/journal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/techniques'
    | '/terms'
    | '/vent'
    | '/verify'
    | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreatheRoute: typeof BreatheRoute
  FaceRoute: typeof FaceRoute
  JournalRoute: typeof JournalRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechniquesRoute: typeof TechniquesRoute
  TermsRoute: typeof TermsRoute
  VentRoute: typeof VentRoute
  VerifyRoute: typeof VerifyRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vent': {
      id: '/vent'
      path: '/vent'
      fullPath: '/vent'
      preLoaderRoute: typeof VentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techniques': {
      id: '/techniques'
      path: '/techniques'
      fullPath: '/techniques'
      preLoaderRoute: typeof TechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face': {
      id: '/face'
      path: '/face'
      fullPath: '/face'
      preLoaderRoute: typeof FaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreatheRoute: BreatheRoute,
  FaceRoute: FaceRoute,
  JournalRoute: JournalRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechniquesRoute: TechniquesRoute,
  TermsRoute: TermsRoute,
  VentRoute: VentRoute,
  VerifyRoute: VerifyRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
